---
- 
  hosts: linux
  become: true
  gather_facts: false
  
    
  vars:
    named_lists:
          - item1
          - item2
          - item3
          - item4
  tasks:
    - name: accessing value type1
      debug:
        msg: "{{ named_lists }}"

    - name: accessing value typ2
      debug: 
        msg: "{{ named_lists.0 }}"

    - name: accessing value typ3
      debug: 
        msg: "{{ named_lists[0] }}"
  
