---
- hosts: redhat
  become: true
  tasks: 
     - name: ensure apache is running
       service:
         name: httpd
         state: started
       notify: restart apache
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
